services:
  api:
    build: ./src/backend
    container_name: api_c
    ports:
      - '9000:9000'
    volumes: 
      - ./api:/app
      - ./api/node_modules
  frontend:
    build: ./
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
